apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:        
    app: myapp
    type: front-end
spec:            
  containers:    
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      env:                  # list of environment variables
        - name: APP_OS      # hardcoded env variable
          value: linux
        - name: MYSQL_HOST  # inject one field from config map
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MYSQL_HOST
      envFrom:              # inject entire config map
        - configMapRef:
            name: app-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MYSQL_USERNAME: root
  MYSQL_HOST: 192.168.1.2
