apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  securityContext: # security on pod level
    runAsUser: 1000
  containers:
    - name: nginx
      image: nginx
      command: ["sleep", "3600"]
      securityContext:  # security on container level
        runAsUser: 1000
        capabilities:   # add privileges (only supported at container level, not at Pod level)
          add: ["MAC_ADMIN"]
