apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod # string
  labels:         # dictionary
    app: myapp
    type: front-end
spec:             # dictionary
  containers:     # list (because pods can have multiple containers)
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep"]  # Entrypoint
      args: ["10"]        # CMD
