apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:                 # replication controller
  template:           # pod template
    metadata:         # metadata of pod
      name: myapp-pod 
      labels:         
        app: myapp
        type: front-end
    spec:             # pod spec
      containers:     
        - name: nginx-container
          image: nginx
  replicas: 3         # no. of pod replicas
