apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:  # inject all secrets
            name: app-secret
      env:            # inject a particular secret
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: another-secret
              key: REDIS_PASSWORD

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:   # values must be encoded (echo -n <value> | base64)
  DB_PASSWORD: cGFzc3dvcmQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: another-secret
data:   # values must be encoded (echo -n <value> | base64)
  REDIS_PASSWORD: amlld2Vp
