apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD ANNOTATION (only us to rewrite the url, e.g., remove /api)
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # For HTTPS
    # cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    # force users to always use https instead of http by redirecting users
    # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  # For HTTPS
  #   tls:
  #     - hosts:
  #         - k8s-multi.com
  #         - www.k8s-multi.com
  #       secretName: yourdomain.com
  rules:
    - http:
        paths:
          - path: /?(.*)
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: server-cluster-ip-service
                port:
                  number: 5000

  # for https configuration
  # rules:
  #   - host: yourdomain.com
  #     http:
  #       paths:
  #         - path: /?(.*)
  #           # UPDATE PATH
  #           pathType: Prefix
  #           # ADD PATHTYPE
  #           backend:
  #             service:
  #               # UPDATE SERVICE FIELDS
  #               name: client-cluster-ip-service
  #               port:
  #                 number: 3000
  #         - path: /api/?(.*)
  #           # UPDATE PATH
  #           pathType: Prefix
  #           # ADD PATHTYPE
  #           backend:
  #             service:
  #               # UPDATE SERVICE FIELDS
  #               name: server-cluster-ip-service
  #               port:
  #                 number: 5000
  #   - host: www.yourdomain.com
  #     http:
  #       paths:
  #         - path: /?(.*)
  #           # UPDATE PATH
  #           pathType: Prefix
  #           # ADD PATHTYPE
  #           backend:
  #             service:
  #               # UPDATE SERVICE FIELDS
  #               name: client-cluster-ip-service
  #               port:
  #                 number: 3000
  #         - path: /api/?(.*)
  #           # UPDATE PATH
  #           pathType: Prefix
  #           # ADD PATHTYPE
  #           backend:
  #             service:
  #               # UPDATE SERVICE FIELDS
  #               name: server-cluster-ip-service
  #               port:
  #                 number: 5000
