apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namePrefix: dev-

images:
  - name: nginx:1.24
    newName: nginx
    newTag: "1.25"

labels:
  - pairs:
      env: development
    includeSelectors: true
    includeTemplates: true

replicas:
  - name: app-deploy
    count: 3
