sudo: required

services:
  - docker

before_install:
  - docker build -t leonlow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true leonlow/react-test npm run test

after_success:
  - docker build -t leonlow/multi-client ./client
  - docker build -t leonlow/multi-nginx ./nginx
  - docker build -t leonlow/multi-server ./server
  - docker build -t leonlow/multi-worker ./worker
  # Run `docker login` to login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push leonlow/multi-client
  - docker push leonlow/multi-nginx
  - docker push leonlow/multi-server
  - docker push leonlow/multi-worker
