sudo: required

services:
  - docker

before_install:
  - docker build -t leonlow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true leonlow/react-test npm run test

after_success:
  - docker build -t leonlow/multi-client ./client
  - docker build -t leonlow/multi-nginx ./nginx
  - docker build -t leonlow/multi-server ./server
  - docker build -t leonlow/multi-worker ./worker