version: "3"
services:
  web:
    # for Dockerfile.dev
    build:
      context: . # all files for the project
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # $(pwd):/app
